# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: comp4513_asgn2-backend

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
    - uses: actions/checkout@v2

    - uses: Generate Env File
      run: |
        cat <<EOF >>.env
        MONGO_USER=${{ secrets.MONGO_USER }}
        MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
        MONGO_URL=${{ secrets.MONGO_URL }}
        EOF
      #from https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
      # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY}}

    # Configure gcloud CLI
    - name: gcloud Set up
      run: |
        gcloud config set project $PROJECT_ID

    - name: deploy to appengine
      run: |
        gcloud app deploy

